services:
 zookeeper:
   image: zookeeper:3.7.0
   container_name: zookeeper_container
   ports:
     - "2181:2181"

 kafaka:
   image: wurstmeister/kafka:latest
   container_name: kafka_container
   ports:
     - "9092:9092"
   environment:
     KAFKA_LISTENERS : PLAINTEXT://0.0.0.0:9092 
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
